"""
PhotoMetadata and MetadataFile models for structured metadata handling.

This module provides proper models for:
1. PhotoMetadata - Structured EXIF/metadata extracted from photos
2. MetadataFile - XMP sidecars and other metadata files

Benefits over current approach:
- Typed fields instead of JSON blob (exif_json)
- Proper foreign key relationships
- Versioning for metadata changes
- Support for multiple metadata sources (embedded, sidecar, user-edited)
- Clear separation between camera metadata and derived metadata
"""

import numbers
import re
import uuid
from datetime import datetime
from fractions import Fraction

from django.db import models
from django.utils.dateparse import parse_datetime

from api.metadata.reader import get_metadata
from api.metadata.tags import Tags
from api.models.user import User, get_deleted_user


class MetadataFile(models.Model):
    """
    Represents a metadata sidecar file (XMP, JSON, etc.) associated with a photo.

    A photo can have multiple metadata files:
    - XMP sidecar from camera/software
    - Adobe Lightroom .xmp
    - Darktable .xmp
    - User-created metadata file
    """

    class FileType(models.TextChoices):
        XMP = "xmp", "XMP Sidecar"
        JSON = "json", "JSON Metadata"
        EXIF = "exif", "EXIF Extract"
        OTHER = "other", "Other"

    class Source(models.TextChoices):
        # Sidecar that came with the photo (same directory)
        ORIGINAL = "original", "Original Sidecar"
        # Generated by photo editing software
        SOFTWARE = "software", "Software Generated"
        # Created by LibrePhotos
        LIBREPHOTOS = "librephotos", "LibrePhotos Generated"
        # User manually created/uploaded
        USER = "user", "User Created"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Link to the File model for actual file storage
    file = models.OneToOneField(
        "File",
        on_delete=models.CASCADE,
        related_name="metadata_info",
    )

    # The photo this metadata belongs to
    photo = models.ForeignKey(
        "Photo",
        on_delete=models.CASCADE,
        related_name="metadata_files",
    )

    file_type = models.CharField(
        max_length=10,
        choices=FileType.choices,
        default=FileType.XMP,
    )

    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.ORIGINAL,
    )

    # Priority for metadata resolution (higher = more authoritative)
    # User edits > Software sidecars > Original sidecars > Embedded
    priority = models.IntegerField(default=0)

    # Software that created this file (if known)
    creator_software = models.CharField(max_length=100, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-priority", "-updated_at"]
        verbose_name = "Metadata File"
        verbose_name_plural = "Metadata Files"

    def __str__(self):
        return f"{self.file_type} sidecar for {self.photo_id}"


class PhotoMetadata(models.Model):
    """
    Structured metadata for a photo.

    This model stores extracted and computed metadata in typed fields,
    making it queryable and more maintainable than a JSON blob.

    Metadata Sources (in priority order):
    1. User edits (highest priority)
    2. XMP sidecar files
    3. Embedded EXIF/IPTC/XMP
    4. Computed/derived values (lowest priority)
    """

    class Source(models.TextChoices):
        # Embedded in the file (EXIF, IPTC, embedded XMP)
        EMBEDDED = "embedded", "Embedded in File"
        # From XMP sidecar file
        SIDECAR = "sidecar", "XMP Sidecar"
        # User manually edited
        USER_EDIT = "user_edit", "User Edit"
        # Computed by LibrePhotos (AI, geocoding, etc.)
        COMPUTED = "computed", "Computed"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    photo = models.OneToOneField(
        "Photo",
        on_delete=models.CASCADE,
        related_name="metadata",
    )

    # ==================== Camera Settings ====================
    # Aperture (f-stop), e.g., 2.8
    aperture = models.FloatField(null=True, blank=True, db_index=True)

    # Shutter speed as a string fraction, e.g., "1/250"
    shutter_speed = models.CharField(max_length=20, null=True, blank=True)

    # Shutter speed in seconds (for queries), e.g., 0.004
    shutter_speed_seconds = models.FloatField(null=True, blank=True)

    # ISO sensitivity
    iso = models.IntegerField(null=True, blank=True, db_index=True)

    # Focal length in mm
    focal_length = models.FloatField(null=True, blank=True)

    # 35mm equivalent focal length
    focal_length_35mm = models.IntegerField(null=True, blank=True)

    # Exposure compensation in EV
    exposure_compensation = models.FloatField(null=True, blank=True)

    # Flash fired
    flash_fired = models.BooleanField(null=True, blank=True)

    # Metering mode
    metering_mode = models.CharField(max_length=50, null=True, blank=True)

    # White balance
    white_balance = models.CharField(max_length=50, null=True, blank=True)

    # ==================== Camera/Lens Info ====================
    camera_make = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    camera_model = models.CharField(
        max_length=100, null=True, blank=True, db_index=True
    )
    lens_make = models.CharField(max_length=100, null=True, blank=True)
    lens_model = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    serial_number = models.CharField(max_length=100, null=True, blank=True)

    # ==================== Image Properties ====================
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    orientation = models.IntegerField(null=True, blank=True)
    color_space = models.CharField(max_length=50, null=True, blank=True)
    bit_depth = models.IntegerField(null=True, blank=True)

    # ==================== Timestamps ====================
    # Original capture time from EXIF
    date_taken = models.DateTimeField(null=True, blank=True, db_index=True)

    # Sub-second precision (from EXIF:SubSecTimeOriginal)
    date_taken_subsec = models.CharField(max_length=10, null=True, blank=True)

    # When the file was last modified
    date_modified = models.DateTimeField(null=True, blank=True)

    # Timezone offset if available
    timezone_offset = models.CharField(max_length=10, null=True, blank=True)

    # ==================== Location ====================
    gps_latitude = models.FloatField(null=True, blank=True, db_index=True)
    gps_longitude = models.FloatField(null=True, blank=True, db_index=True)
    gps_altitude = models.FloatField(null=True, blank=True)

    # Location from reverse geocoding
    location_country = models.CharField(
        max_length=100, null=True, blank=True, db_index=True
    )
    location_state = models.CharField(max_length=100, null=True, blank=True)
    location_city = models.CharField(
        max_length=100, null=True, blank=True, db_index=True
    )
    location_address = models.TextField(null=True, blank=True)

    # ==================== Content Description ====================
    title = models.CharField(max_length=500, null=True, blank=True)
    caption = models.TextField(null=True, blank=True)
    keywords = models.JSONField(null=True, blank=True)  # List of strings

    # Rating (0-5 stars)
    rating = models.IntegerField(null=True, blank=True, db_index=True)

    # Copyright info
    copyright = models.TextField(null=True, blank=True)
    creator = models.CharField(max_length=200, null=True, blank=True)

    # ==================== Tracking ====================
    # Which source this metadata came from
    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.EMBEDDED,
    )

    # Raw EXIF/XMP data for fields we don't have explicit columns for
    raw_exif = models.JSONField(null=True, blank=True)
    raw_xmp = models.JSONField(null=True, blank=True)
    raw_iptc = models.JSONField(null=True, blank=True)

    # Version tracking
    version = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Photo Metadata"
        verbose_name_plural = "Photo Metadata"
        indexes = [
            models.Index(fields=["camera_make", "camera_model"]),
            models.Index(fields=["date_taken"]),
            models.Index(fields=["location_country", "location_city"]),
        ]

    def __str__(self):
        return f"Metadata for {self.photo_id}"

    @property
    def resolution(self):
        """Returns resolution as 'WxH' string."""
        if self.width and self.height:
            return f"{self.width}x{self.height}"
        return None

    @property
    def megapixels(self):
        """Returns megapixel count."""
        if self.width and self.height:
            return round((self.width * self.height) / 1_000_000, 1)
        return None

    @property
    def has_location(self):
        """Check if GPS coordinates are available."""
        return self.gps_latitude is not None and self.gps_longitude is not None

    @property
    def camera_display(self):
        """Returns a human-readable camera name."""
        if self.camera_make and self.camera_model:
            # Avoid duplicating make in model
            if self.camera_model.startswith(self.camera_make):
                return self.camera_model
            return f"{self.camera_make} {self.camera_model}"
        return self.camera_model or self.camera_make

    @property
    def lens_display(self):
        """Returns a human-readable lens name."""
        if self.lens_make and self.lens_model:
            if self.lens_model.startswith(self.lens_make):
                return self.lens_model
            return f"{self.lens_make} {self.lens_model}"
        return self.lens_model or self.lens_make

    @classmethod
    def _is_blank_value(cls, value):
        if value is None:
            return True
        if isinstance(value, str):
            return value == ""
        if isinstance(value, (list, tuple, dict, set)):
            return len(value) == 0
        return False

    @classmethod
    def _set_if_present(cls, obj, field_name, value, update_fields, overwrite):
        if cls._is_blank_value(value):
            return

        current_value = getattr(obj, field_name)
        if overwrite or cls._is_blank_value(current_value):
            setattr(obj, field_name, value)
            update_fields.add(field_name)

    @staticmethod
    def _normalize_keywords(value):
        if value is None:
            return None
        if isinstance(value, dict):
            for dict_value in value.values():
                normalized = PhotoMetadata._normalize_keywords(dict_value)
                if normalized:
                    return normalized
            return None
        if isinstance(value, list):
            normalized = [str(item).strip() for item in value if str(item).strip()]
            return normalized or None
        if isinstance(value, str):
            if "," in value:
                normalized = [item.strip() for item in value.split(",") if item.strip()]
                return normalized or None
            stripped = value.strip()
            return [stripped] if stripped else None
        return None

    @staticmethod
    def _normalize_text(value, join_list=False):
        if value is None:
            return None
        if isinstance(value, dict):
            preferred_keys = ("x-default", "en-US", "en", "und")
            for key in preferred_keys:
                preferred_value = value.get(key)
                if preferred_value:
                    return str(preferred_value).strip() or None

            for dict_value in value.values():
                normalized = PhotoMetadata._normalize_text(
                    dict_value, join_list=join_list
                )
                if normalized:
                    return normalized
            return None
        if isinstance(value, list):
            items = [str(item).strip() for item in value if str(item).strip()]
            if not items:
                return None
            return ", ".join(items) if join_list else items[0]
        text = str(value).strip()
        return text or None

    @staticmethod
    def _normalize_datetime(value):
        if value is None:
            return None
        if isinstance(value, datetime):
            return value
        if isinstance(value, list):
            for item in value:
                normalized = PhotoMetadata._normalize_datetime(item)
                if normalized is not None:
                    return normalized
            return None
        if isinstance(value, dict):
            for item in value.values():
                normalized = PhotoMetadata._normalize_datetime(item)
                if normalized is not None:
                    return normalized
            return None

        text_value = str(value).strip()
        if not text_value:
            return None

        parsed_value = parse_datetime(text_value)
        if parsed_value is not None:
            return parsed_value

        exif_formats = (
            "%Y:%m:%d %H:%M:%S%z",
            "%Y:%m:%d %H:%M:%S",
            "%Y-%m-%d %H:%M:%S%z",
            "%Y-%m-%d %H:%M:%S",
        )
        for exif_format in exif_formats:
            try:
                return datetime.strptime(text_value, exif_format)
            except ValueError:
                continue

        return None

    @staticmethod
    def _normalize_float(value):
        if value is None:
            return None
        if isinstance(value, numbers.Number):
            return float(value)
        if isinstance(value, list):
            for item in value:
                normalized = PhotoMetadata._normalize_float(item)
                if normalized is not None:
                    return normalized
            return None
        if isinstance(value, dict):
            for item in value.values():
                normalized = PhotoMetadata._normalize_float(item)
                if normalized is not None:
                    return normalized
            return None

        text_value = str(value).strip()
        if not text_value:
            return None
        if "/" in text_value:
            try:
                return float(Fraction(text_value))
            except (ValueError, ZeroDivisionError):
                pass

        match = re.search(r"-?\d+(?:\.\d+)?", text_value)
        if match:
            try:
                return float(match.group(0))
            except ValueError:
                return None
        return None

    @staticmethod
    def _normalize_int(value):
        normalized = PhotoMetadata._normalize_float(value)
        if normalized is None:
            return None
        return int(normalized)

    @classmethod
    def extract_exif_data(cls, photo, commit=True, overwrite=True, try_sidecar=True):
        """
        Extract EXIF data from a photo's main file and update PhotoMetadata.

        This method extracts metadata from the photo's main file and:
        1. Updates Photo fields (size, video_length, rating, exif_timestamp_subsec, image_sequence_number)
        2. Gets or creates PhotoMetadata and populates it with extracted data

        Args:
            photo: Photo instance to extract metadata from
            commit: Whether to save Photo and PhotoMetadata after extraction
            overwrite: Whether extracted values should replace existing metadata
            try_sidecar: Whether sidecar metadata should override embedded metadata

        Returns:
            PhotoMetadata instance
        """
        if not photo.main_file:
            return None

        requested_tags = [
            Tags.FILE_SIZE,
            Tags.FSTOP,
            Tags.FOCAL_LENGTH,
            Tags.ISO,
            Tags.EXPOSURE_TIME,
            Tags.CAMERA_MAKE,
            Tags.CAMERA,
            Tags.LENS_MAKE,
            Tags.LENS,
            Tags.IMAGE_WIDTH,
            Tags.IMAGE_HEIGHT,
            Tags.FOCAL_LENGTH_35MM,
            Tags.SUBJECT_DISTANCE,
            Tags.DIGITAL_ZOOM_RATIO,
            Tags.QUICKTIME_DURATION,
            Tags.RATING,
            Tags.SUBSEC_TIME_ORIGINAL,
            Tags.IMAGE_NUMBER,
            Tags.DATE_TIME_ORIGINAL,
            Tags.QUICKTIME_CREATE_DATE,
            Tags.TIMEZONE_OFFSET,
            Tags.LATITUDE,
            Tags.LONGITUDE,
            Tags.GPS_ALTITUDE,
            Tags.TITLE,
            Tags.DESCRIPTION,
            Tags.SUBJECT,
            Tags.IPTC_KEYWORDS,
            Tags.CREATOR,
            Tags.COPYRIGHT,
            Tags.ORIENTATION,
            Tags.COLOR_SPACE,
            Tags.BIT_DEPTH,
            Tags.SERIAL_NUMBER,
            Tags.FILE_MODIFY_DATE,
        ]
        tag_values = dict(
            zip(
                requested_tags,
                get_metadata(
                    photo.main_file.path,
                    tags=requested_tags,
                    try_sidecar=try_sidecar,
                ),
            )
        )

        size = tag_values.get(Tags.FILE_SIZE)
        fstop = cls._normalize_float(tag_values.get(Tags.FSTOP))
        focal_length = cls._normalize_float(tag_values.get(Tags.FOCAL_LENGTH))
        iso = cls._normalize_int(tag_values.get(Tags.ISO))
        shutter_speed = tag_values.get(Tags.EXPOSURE_TIME)
        camera_make = cls._normalize_text(tag_values.get(Tags.CAMERA_MAKE))
        camera = cls._normalize_text(tag_values.get(Tags.CAMERA))
        lens_make = cls._normalize_text(tag_values.get(Tags.LENS_MAKE))
        lens = cls._normalize_text(tag_values.get(Tags.LENS))
        width = cls._normalize_int(tag_values.get(Tags.IMAGE_WIDTH))
        height = cls._normalize_int(tag_values.get(Tags.IMAGE_HEIGHT))
        focal_length_35mm = cls._normalize_int(tag_values.get(Tags.FOCAL_LENGTH_35MM))
        video_length = cls._normalize_float(tag_values.get(Tags.QUICKTIME_DURATION))
        rating = cls._normalize_int(tag_values.get(Tags.RATING))
        subsec_time_original = cls._normalize_text(tag_values.get(Tags.SUBSEC_TIME_ORIGINAL))
        image_number = cls._normalize_int(tag_values.get(Tags.IMAGE_NUMBER))
        date_taken = cls._normalize_datetime(
            tag_values.get(Tags.DATE_TIME_ORIGINAL)
            or tag_values.get(Tags.QUICKTIME_CREATE_DATE)
        )
        timezone_offset = cls._normalize_text(tag_values.get(Tags.TIMEZONE_OFFSET))
        gps_latitude = cls._normalize_float(tag_values.get(Tags.LATITUDE))
        gps_longitude = cls._normalize_float(tag_values.get(Tags.LONGITUDE))
        gps_altitude = cls._normalize_float(tag_values.get(Tags.GPS_ALTITUDE))
        title = cls._normalize_text(tag_values.get(Tags.TITLE))
        caption = cls._normalize_text(tag_values.get(Tags.DESCRIPTION))
        xmp_subject = tag_values.get(Tags.SUBJECT)
        iptc_keywords = tag_values.get(Tags.IPTC_KEYWORDS)
        keywords = cls._normalize_keywords(
            xmp_subject or iptc_keywords
        )
        creator = cls._normalize_text(tag_values.get(Tags.CREATOR), join_list=True)
        copyright_value = cls._normalize_text(tag_values.get(Tags.COPYRIGHT))
        orientation = cls._normalize_int(tag_values.get(Tags.ORIENTATION))
        color_space = cls._normalize_text(tag_values.get(Tags.COLOR_SPACE))
        bit_depth = cls._normalize_int(tag_values.get(Tags.BIT_DEPTH))
        serial_number = cls._normalize_text(tag_values.get(Tags.SERIAL_NUMBER))
        date_modified = cls._normalize_datetime(tag_values.get(Tags.FILE_MODIFY_DATE))

        photo_update_fields = set()
        metadata_update_fields = set()

        # Fields still on Photo model
        if isinstance(size, numbers.Number):
            photo.size = size
            photo_update_fields.add("size")
        if isinstance(video_length, numbers.Number):
            photo.video_length = video_length
            photo_update_fields.add("video_length")
        if isinstance(rating, numbers.Number):
            photo.rating = rating
            photo_update_fields.add("rating")
        if isinstance(gps_latitude, numbers.Number):
            photo.exif_gps_lat = float(gps_latitude)
            photo_update_fields.add("exif_gps_lat")
        if isinstance(gps_longitude, numbers.Number):
            photo.exif_gps_lon = float(gps_longitude)
            photo_update_fields.add("exif_gps_lon")

        # Burst/sequence detection fields
        if subsec_time_original:
            # SubSecTimeOriginal is typically a string like "123" representing milliseconds
            photo.exif_timestamp_subsec = str(subsec_time_original)[:10]
            photo_update_fields.add("exif_timestamp_subsec")
        if isinstance(image_number, numbers.Number):
            photo.image_sequence_number = int(image_number)
            photo_update_fields.add("image_sequence_number")

        if commit and photo_update_fields:
            photo.save(update_fields=sorted(photo_update_fields), save_metadata=False)

        # Store metadata in PhotoMetadata model
        metadata, _created = cls.objects.get_or_create(
            photo=photo, defaults={"source": cls.Source.EMBEDDED}
        )

        cls._set_if_present(metadata, "aperture", fstop, metadata_update_fields, overwrite)
        cls._set_if_present(
            metadata, "focal_length", focal_length, metadata_update_fields, overwrite
        )
        cls._set_if_present(metadata, "iso", iso, metadata_update_fields, overwrite)
        cls._set_if_present(
            metadata,
            "camera_make",
            camera_make,
            metadata_update_fields,
            overwrite,
        )
        cls._set_if_present(
            metadata, "camera_model", camera, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata, "lens_make", lens_make, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata, "lens_model", lens, metadata_update_fields, overwrite
        )
        cls._set_if_present(metadata, "width", width, metadata_update_fields, overwrite)
        cls._set_if_present(
            metadata, "height", height, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata,
            "focal_length_35mm",
            focal_length_35mm,
            metadata_update_fields,
            overwrite,
        )
        cls._set_if_present(
            metadata, "rating", rating, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata,
            "date_taken",
            date_taken,
            metadata_update_fields,
            overwrite,
        )
        cls._set_if_present(
            metadata,
            "timezone_offset",
            timezone_offset,
            metadata_update_fields,
            overwrite,
        )
        if isinstance(gps_latitude, numbers.Number):
            cls._set_if_present(
                metadata,
                "gps_latitude",
                float(gps_latitude),
                metadata_update_fields,
                overwrite,
            )
        if isinstance(gps_longitude, numbers.Number):
            cls._set_if_present(
                metadata,
                "gps_longitude",
                float(gps_longitude),
                metadata_update_fields,
                overwrite,
            )
        if isinstance(gps_altitude, numbers.Number):
            cls._set_if_present(
                metadata,
                "gps_altitude",
                float(gps_altitude),
                metadata_update_fields,
                overwrite,
            )
        cls._set_if_present(metadata, "title", title, metadata_update_fields, overwrite)
        cls._set_if_present(
            metadata, "caption", caption, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata, "keywords", keywords, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata, "creator", creator, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata,
            "copyright",
            copyright_value,
            metadata_update_fields,
            overwrite,
        )
        cls._set_if_present(
            metadata,
            "orientation",
            orientation,
            metadata_update_fields,
            overwrite,
        )
        cls._set_if_present(
            metadata,
            "color_space",
            color_space,
            metadata_update_fields,
            overwrite,
        )
        cls._set_if_present(
            metadata, "bit_depth", bit_depth, metadata_update_fields, overwrite
        )
        cls._set_if_present(
            metadata,
            "serial_number",
            serial_number,
            metadata_update_fields,
            overwrite,
        )
        cls._set_if_present(
            metadata,
            "date_modified",
            date_modified,
            metadata_update_fields,
            overwrite,
        )

        # Merge keywords from XMP:Subject and IPTC:Keywords (deduplicated)
        merged_keywords = set()
        if xmp_subject:
            if isinstance(xmp_subject, list):
                merged_keywords.update(xmp_subject)
            elif isinstance(xmp_subject, str):
                merged_keywords.add(xmp_subject)
        if iptc_keywords:
            if isinstance(iptc_keywords, list):
                merged_keywords.update(iptc_keywords)
            elif isinstance(iptc_keywords, str):
                merged_keywords.add(iptc_keywords)
        if merged_keywords:
            metadata.keywords = sorted(merged_keywords)
        if commit:
            metadata.save()

        if isinstance(shutter_speed, numbers.Number):
            cls._set_if_present(
                metadata,
                "shutter_speed_seconds",
                float(shutter_speed),
                metadata_update_fields,
                overwrite,
            )
            cls._set_if_present(
                metadata,
                "shutter_speed",
                str(Fraction(shutter_speed).limit_denominator(1000)),
                metadata_update_fields,
                overwrite,
            )
        elif isinstance(shutter_speed, str):
            cls._set_if_present(
                metadata,
                "shutter_speed",
                shutter_speed,
                metadata_update_fields,
                overwrite,
            )

        if subsec_time_original:
            cls._set_if_present(
                metadata,
                "date_taken_subsec",
                str(subsec_time_original)[:10],
                metadata_update_fields,
                overwrite,
            )

        if commit and metadata_update_fields:
            metadata.save(update_fields=sorted(metadata_update_fields))

        return metadata


class MetadataEdit(models.Model):
    """
    Tracks user edits to photo metadata for history/undo functionality.

    Each edit records what field was changed, old value, new value,
    and who made the change.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    photo = models.ForeignKey(
        "Photo",
        on_delete=models.CASCADE,
        related_name="metadata_edits",
    )

    user = models.ForeignKey(
        User,
        on_delete=models.SET(get_deleted_user),
        related_name="metadata_edits",
    )

    # Which field was edited
    field_name = models.CharField(max_length=100)

    # JSON-serialized old and new values
    old_value = models.JSONField(null=True, blank=True)
    new_value = models.JSONField(null=True, blank=True)

    # Whether this edit has been written back to the file
    synced_to_file = models.BooleanField(default=True)
    synced_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Metadata Edit"
        verbose_name_plural = "Metadata Edits"
        indexes = [
            models.Index(fields=["photo", "-created_at"]),
        ]

    def __str__(self):
        return f"Edit {self.field_name} on {self.photo_id}"
